### ISSUE TITLE
Fps of video

### ISSUE THREAD

**Issue by Surupor** [hxixixh/mix-and-localize#4]
Hello, I want to ask, does the fps=4 here need to resample itself? The fps of the original video is 28.99 fps.

data
  └──MUSIC 
  │    ├──data-splits
  │    ├──MUSIC_raw
  │           ├──duet
  │           ├──solo
  │                └── [class_label]
  │                         └── [ytid]
  │                               ├── audio
  │                               │      ├──audio_clips
  │                               │             ├── 00000.wav       # 1 second audio clips
  │                               │             ├── 00001.wav
  │                               │             ├── ...
  │                               └── frames
  │                                      ├── 00000.jpg              **# fps = 4**
  │                                      ├── ...

**Comment by hxixixh** [comment]
Hi @Surupor , yes we resampled frames to be 4 fps

**Comment by Surupor** [comment]
> 

thanks
