### ISSUE TITLE
Version of Python and Pytorch？

### ISSUE THREAD

**Issue by Protaib** [hxixixh/mix-and-localize#6]
Hi! Could you please tell me about the versions of **_Python_** and **_Pytorch_**? It would be nice to provide `requirements.txt`! 

Thank you!

**Comment by hxixixh** [comment]
Hi @Protaib,

Thanks for reaching out! I apologize, but I don't have the exact versions of Python and PyTorch that were used for this project readily available. However, I recommend trying the latest stable versions of both. If you encounter any issues, please feel free to report them here.
